set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'godlygeek/tabular'
Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'tpope/vim-dispatch'
Plugin 'vim-scripts/Solarized'
Plugin 'shawncplus/skittles_berry'
Plugin 'chandlerc/jellybeans.vim'
Plugin 'mileszs/ack.vim'

call vundle#end()            " required
filetype plugin indent on    " required
syntax on


let mapleader = ','


set t_Co=256
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set showcmd
set nonumber
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=2
set autoindent
set formatoptions=c,q,r,t
set ruler
set background=dark
set laststatus=2
set undolevels=200
set nobackup
set noswapfile
set noerrorbells
set hidden
set wrapscan
set wildmenu
set nowrap
set pastetoggle=<F12>
set timeoutlen=100
set scrolloff=5

set nobackup
set nowritebackup

colorscheme jellybeans


" Aliases {
  nnoremap <leader><CR> :nohlsearch<CR>
  " Quickly edit/reload the vimrc file
  nmap <silent> <leader>ev :e $MYVIMRC<CR>
  nmap <silent> <leader>sv :so $MYVIMRC<CR>
  nnoremap j gj
  nnoremap k gk

  nnoremap <leader>r :! runhaskell %<CR>
  nmap <C-n> :NERDTreeToggle<CR>



""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins specific
""""""""""""""""""""""""""""""""""""""""""""""""""""""
" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlPBuffer'

